version: "3.7"
services:
  apiservice:
    image: mirkitobtw/marketplace-image
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/marketplace-api?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
    depends_on:
      - mysqldb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  frontend:
    image: mirkitobtw/marketplace-frontend-image
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    depends_on:
      - apiservice
    environment:
      - API_PORT=apiservice:8080
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mysqldb:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=marketplace-api

volumes:
  pgdata:

networks:
  springapimysql-net: